<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE dwwm_2021 [
    <!ELEMENT <dwwm_2021> (prenom+, nom, age, genre?, site_perso?, info_confinement, info_dev)>
    <!-- DTD pour la civilité -->
    <!ELEMENT prenom (#PCDATA)>
    <!ELEMENT nom (#PCDATA)>
    <!ELEMENT age (#PCDATA)>
    <!ELEMENT genre (masculin|feminin) >
    <!ELEMENT masculin EMPTY >
    <!ELEMENT feminin EMPTY >
    <!ELEMENT site_perso (#PCDATA)>
    <!-- DTD pour le confinement-->
    <!ELEMENT info_confinement (nombre_de_personne, lieu)>
    <!ELEMENT nombre_de_personne (nombre_adulte, nombre_enfant?)>
    <!ELEMENT nombre_adulte (#PCDATA)>
    <!ELEMENT nombre_enfant (#PCDATA)>
    <!ELEMENT lieu (commune, type, surface, jardin)>
    <!ELEMENT commune (#PCDATA)>
    <!ELEMENT type (#PCDATA) >
    <!ELEMENT surface (#PCDATA) >
    <!ELEMENT jardin (jardin_presence, jardin_surface?) >
    <!ELEMENT jardin_presence (#PCDATA)>
    <!ELEMENT jardin_surface (#PCDATA) >
    <!-- DTD pour lales infos de dev -->
    <!ELEMENT info_dev (langage_deja_utilise*, nombre_de_site_developpe?, exemple_de_site_developpe?)>
    <!ELEMENT langage_deja_utilise (XML | HTML | CSS | SASS | LESSCSS | BOOTSTRAP | MATERIALIZE | FOUNDATION | JS | TYPESCRIPT | COFFEESCRIPT | JQUERY | ANGULARJS | NODEJS | REACTJS | VUEJS | ANGULAR | PHP | SYMFONY | LARAVEL | WORDPRESS )*>
    <!ELEMENT XML EMPTY >
    <!ELEMENT HTML EMPTY >
    <!ELEMENT CSS EMPTY >
    <!ELEMENT SASS EMPTY >
    <!ELEMENT LESSCSS EMPTY >
    <!ELEMENT BOOTSTRAP EMPTY >
    <!ELEMENT MATERIALIZE EMPTY >
    <!ELEMENT FOUNDATION EMPTY >
    <!ELEMENT JS EMPTY >
    <!ELEMENT TYPESCRIPT EMPTY >
    <!ELEMENT COFFEESCRIPT EMPTY >
    <!ELEMENT JQUERY EMPTY >
    <!ELEMENT ANGULARJS EMPTY >
    <!ELEMENT NODEJS EMPTY >
    <!ELEMENT REACTJS EMPTY >
    <!ELEMENT VUEJS EMPTY >
    <!ELEMENT ANGULAR EMPTY >
    <!ELEMENT PHP EMPTY >
    <!ELEMENT SYMFONY EMPTY >
    <!ELEMENT LARAVEL EMPTY >
    <!ELEMENT WORDPRESS EMPTY >
    <!ELEMENT C EMPTY>
    <!ELEMENT PYTHON EMPTY>
    <!ELEMENT NODEJS EMPTY>
    <!ELEMENT MYSQL EMPTY>
    <!ELEMENT nombre_de_site_developpe (#PCDATA) >
    <!ELEMENT exemple_de_site_developpe (#PCDATA) >
]>

<dwwm_2021>
    <!-- civilité -->
    <prenom>Vincent</prenom>
    <nom>Fracas</nom>
    <age>25</age>
    <genre>
        <masculin />
    </genre>
    <!-- confinement de 2021 -->
    <info_confinement>
        <nombre_de_personne>
            <nb_adulte>2</nb_adulte>
        </nombre_de_personne>
        <lieu>
            <commune>Monistrol sur Loire</commune>
            <type>Appartement</type>
            <jardin>
                <jardin_presence>Non</jardin_presence>
            </jardin>
        </lieu>
    </info_confinement>
    <!-- infos de dev -->
    <info_dev>
        <site_perso>En cours de refonte</site_perso>
        <langage_deja_utilise>
            <HTML />
            <CSS />
            <BOOTSTRAP />
            <JS />
            <REACTJS />
            <NODEJS />
            <WORDPRESS />
            <MYSQL />
            <PHP />
            <LARAVEL />
            <C />
            <PYTHON />
        </langage_deja_utilise>
        <nombre_de_site_developpe>Pas beaucoup</nombre_de_site_developpe>
    </info_dev>
</dwwm_2021>
